/boat1/boat_simulation_node:
  ros__parameters:
    initial_x: 0.0
    initial_y: 0.0
    initial_theta: 0.0

/boat2/boat_simulation_node:
  ros__parameters:
    initial_x: 100.0
    initial_y: 10.0
    initial_theta: 0.5

/boat3/boat_simulation_node:
  ros__parameters:
    initial_x: 200.0
    initial_y: 200.0
    initial_theta: 1.0
